import spacy
import pandas as pd 

df = pd.read_csv('./dataset/dataset.csv')

# ! GENERATED BY CHATGPT 25.02.20
# Load the spaCy English model
nlp = spacy.load("en_core_web_sm")

def clean_text(text):
    # Process the text with spaCy
    doc = nlp(text)
    filtered_tokens = []
    for token in doc:
        # Check if token belongs to an entity of interest
        if token.ent_type_ in {"PERSON", "ORG", "GPE", "LOC"}:
            continue
        # Remove punctuation and stop words
        if token.is_punct or token.is_stop or token.is_digit:
            continue
        filtered_tokens.append(token.text)
    return " ".join(filtered_tokens)

data = df['quote'].apply(clean_text)
# data = clean_text(data)

df['cleaned_text'] = data

df.to_csv('./dataset/cleaned-dataset.csv')